# Generated by Django 4.2.7 on 2025-11-29 08:18

import apps.common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='client_documents/', validators=[apps.common.validators.validate_document_file]),
        ),
        migrations.AddField(
            model_name='client',
            name='collateral_pictures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='identification_picture',
            field=models.ImageField(blank=True, null=True, upload_to='client_ids/', validators=[apps.common.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='client',
            name='loan_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='proof_of_income',
            field=models.FileField(blank=True, null=True, upload_to='client_documents/', validators=[apps.common.validators.validate_document_file]),
        ),
    ]
