# Generated by Django 4.2.7 on 2025-11-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_admin_email_company_subscription_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=50),
        ),
    ]
